package com.recoverwell.core.logic

import com.recoverwell.core.model.JournalEntry
import java.time.LocalDate

/**
 * Pure trend derivation over recovery-journal entries: how consistently the user
 * is checking in and which way their inferred mood is moving. Drives the journal
 * screen's at-a-glance header; the narrative weekly summary is generated by AI.
 */
object JournalTrends {

    enum class Direction { UP, DOWN, FLAT, UNKNOWN }

    data class Trends(
        val total: Int,
        /** Consecutive days with an entry, counting back from today (or yesterday). */
        val streakDays: Int,
        /** Mean mood score over the last 7 days, or null if none. */
        val recentAvgMood: Double?,
        /** Mean mood score over the prior 7 days, or null if none. */
        val priorAvgMood: Double?,
        val direction: Direction,
        val loggedToday: Boolean
    )

    fun compute(entries: List<JournalEntry>, today: LocalDate): Trends {
        if (entries.isEmpty())
            return Trends(0, 0, null, null, Direction.UNKNOWN, false)

        val days = entries.map { it.date }.toHashSet()
        val loggedToday = days.contains(today)

        // streak: walk back day-by-day from today (or yesterday, if not yet logged today)
        var streak = 0
        var cursor = if (loggedToday) today else today.minusDays(1)
        while (days.contains(cursor)) {
            streak++
            cursor = cursor.minusDays(1)
        }

        val recent = entries.filter { !it.date.isBefore(today.minusDays(6)) }
        val prior = entries.filter {
            it.date.isBefore(today.minusDays(6)) && !it.date.isBefore(today.minusDays(13))
        }
        val recentAvg = recent.takeIf { it.isNotEmpty() }?.map { it.mood.score }?.average()
        val priorAvg = prior.takeIf { it.isNotEmpty() }?.map { it.mood.score }?.average()
        val direction = when {
            recentAvg == null || priorAvg == null -> Direction.UNKNOWN
            recentAvg - priorAvg >= 0.5 -> Direction.UP
            priorAvg - recentAvg >= 0.5 -> Direction.DOWN
            else -> Direction.FLAT
        }
        return Trends(entries.size, streak, recentAvg, priorAvg, direction, loggedToday)
    }
}
